# azure-boards-import

# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription 1(1891f709-d05d-47f9-95d1-14d23f0ea673)'
    KeyVaultName: 'azure-boards-import-vt'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: DownloadSecureFile@1
  name: config
  inputs:
    secureFile: 'config.ts'

- task: DownloadSecureFile@1
  name: csv
  inputs:
    secureFile: 'workitems.csv'

- script: cp $(config.secureFilePath) .

- script: cp $(csv.secureFilePath) .

- script: ls -lat

- script: |
    npm run import
  displayName: 'npm import'
